[package]
name = "giti"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"                                                                                     # https://spdx.org/licenses/
authors = ["Elio Grieco <grieco@egx.com>"]
description = "A tool to easily query Git repos for basic information. Can be used via CLI or as a library."
repository = "https://github.com/symplasma/giti"
readme = "README.md"
keywords = ["git", "info", "disk-size", "status"]                                                            # free text
categories = ["command-line-utilities"]                                                                      # https://crates.io/category_slugs
exclude = [".vscode/*", ".gitignore", ".aider.*"]
# https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "giti"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.99"
chrono = "0.4"
chrono-humanize = "0.2.3"
clap = { version = "4.5", features = ["derive"] }
color-eyre = "0.6.5"
gix = "0.73"
yansi = "1.0.1"
